http:
  middlewares:
    https-only:
      redirectScheme:
        scheme: https

    # Pede usuário e senha (basic auth) no painel
    dashboard-auth:
      basicAuth:
        users:
          - 'admin:$2y$05$J1ghx.qkMD8mG0IWgAQHtuZ06n/v48idmIORBvtlrIvdGWrLsPsHW'
